# Generated by Django 4.0.5 on 2022-06-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codigo')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('categoria', models.CharField(max_length=25, verbose_name='Categoria')),
            ],
        ),
    ]
