# Generated by Django 4.0.4 on 2022-06-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('nombre', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('apellido', models.CharField(max_length=25, verbose_name='apellido')),
                ('correo', models.CharField(max_length=25, verbose_name='correo')),
                ('rut', models.CharField(max_length=30, verbose_name='nombre')),
            ],
        ),
    ]
