# Generated by Django 4.0.4 on 2022-06-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0003_alter_cliente_nombre_alter_cliente_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=10, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='rut'),
        ),
    ]
